apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: webapps
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80         # ELB listens on 80
      targetPort: 8080 # Pod listens on 8080
